//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/marco/Desktop/Interpretador MACOY/MACOY/MACOY\MACOY.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ParserJava {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class MACOYLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		INICIO=1, VAR=2, INT=3, IMPRIMIR=4, SI=5, SINO=6, SUMA=7, MENOS=8, MULT=9, 
		DIV=10, MOD=11, AND=12, OR=13, NOT=14, MAYORQUE=15, MENORQUE=16, MAYORIGUAL=17, 
		MENORIGUAL=18, IGUAL=19, DIFERENTE=20, ASIGNACION=21, LLAVE_ABRIR=22, 
		LLAVE_CERRAR=23, PARENTESIS_ABRIR=24, PARENTESIS_CERRAR=25, FINDELINEA=26, 
		BOOLEAN=27, VARIABLE=28, NUMERO=29, ESPACIOENBLANCO=30;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"INICIO", "VAR", "INT", "IMPRIMIR", "SI", "SINO", "SUMA", "MENOS", "MULT", 
		"DIV", "MOD", "AND", "OR", "NOT", "MAYORQUE", "MENORQUE", "MAYORIGUAL", 
		"MENORIGUAL", "IGUAL", "DIFERENTE", "ASIGNACION", "LLAVE_ABRIR", "LLAVE_CERRAR", 
		"PARENTESIS_ABRIR", "PARENTESIS_CERRAR", "FINDELINEA", "BOOLEAN", "VARIABLE", 
		"NUMERO", "ESPACIOENBLANCO"
	};


	public MACOYLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public MACOYLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'MACOY'", "'var'", "'int'", "'moutln'", "'Si'", "'Sino'", "'+'", 
		"'-'", "'*'", "'/'", "'%'", "'&&'", "'||'", "'!'", "'>'", "'<'", "'>='", 
		"'<='", "'=='", "'!='", "'='", "'{'", "'}'", "'('", "')'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "INICIO", "VAR", "INT", "IMPRIMIR", "SI", "SINO", "SUMA", "MENOS", 
		"MULT", "DIV", "MOD", "AND", "OR", "NOT", "MAYORQUE", "MENORQUE", "MAYORIGUAL", 
		"MENORIGUAL", "IGUAL", "DIFERENTE", "ASIGNACION", "LLAVE_ABRIR", "LLAVE_CERRAR", 
		"PARENTESIS_ABRIR", "PARENTESIS_CERRAR", "FINDELINEA", "BOOLEAN", "VARIABLE", 
		"NUMERO", "ESPACIOENBLANCO"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MACOY.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MACOYLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ' ', '\xA8', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x5', '\x1C', '\x94', '\n', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\a', '\x1D', '\x98', '\n', '\x1D', '\f', '\x1D', '\xE', 
		'\x1D', '\x9B', '\v', '\x1D', '\x3', '\x1E', '\x6', '\x1E', '\x9E', '\n', 
		'\x1E', '\r', '\x1E', '\xE', '\x1E', '\x9F', '\x3', '\x1F', '\x6', '\x1F', 
		'\xA3', '\n', '\x1F', '\r', '\x1F', '\xE', '\x1F', '\xA4', '\x3', '\x1F', 
		'\x3', '\x1F', '\x2', '\x2', ' ', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '\x3', '\x2', '\x6', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', 
		'\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\xAB', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '?', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\a', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\t', 'M', '\x3', '\x2', '\x2', '\x2', '\v', 'T', '\x3', '\x2', '\x2', 
		'\x2', '\r', 'W', '\x3', '\x2', '\x2', '\x2', '\xF', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\x11', '^', '\x3', '\x2', '\x2', '\x2', '\x13', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x15', '\x62', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x19', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', 'i', '\x3', '\x2', '\x2', '\x2', '\x1D', 'l', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', 'n', '\x3', '\x2', '\x2', '\x2', '!', 'p', '\x3', 
		'\x2', '\x2', '\x2', '#', 'r', '\x3', '\x2', '\x2', '\x2', '%', 'u', '\x3', 
		'\x2', '\x2', '\x2', '\'', 'x', '\x3', '\x2', '\x2', '\x2', ')', '{', 
		'\x3', '\x2', '\x2', '\x2', '+', '~', '\x3', '\x2', '\x2', '\x2', '-', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '/', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x84', '\x3', '\x2', '\x2', '\x2', '\x33', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x88', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x39', '\x95', '\x3', '\x2', '\x2', 
		'\x2', ';', '\x9D', '\x3', '\x2', '\x2', '\x2', '=', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '?', '@', '\a', 'O', '\x2', '\x2', '@', '\x41', '\a', '\x43', 
		'\x2', '\x2', '\x41', '\x42', '\a', '\x45', '\x2', '\x2', '\x42', '\x43', 
		'\a', 'Q', '\x2', '\x2', '\x43', '\x44', '\a', '[', '\x2', '\x2', '\x44', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', 'x', '\x2', '\x2', 
		'\x46', 'G', '\a', '\x63', '\x2', '\x2', 'G', 'H', '\a', 't', '\x2', '\x2', 
		'H', '\x6', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', 'k', '\x2', '\x2', 
		'J', 'K', '\a', 'p', '\x2', '\x2', 'K', 'L', '\a', 'v', '\x2', '\x2', 
		'L', '\b', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', 'o', '\x2', '\x2', 
		'N', 'O', '\a', 'q', '\x2', '\x2', 'O', 'P', '\a', 'w', '\x2', '\x2', 
		'P', 'Q', '\a', 'v', '\x2', '\x2', 'Q', 'R', '\a', 'n', '\x2', '\x2', 
		'R', 'S', '\a', 'p', '\x2', '\x2', 'S', '\n', '\x3', '\x2', '\x2', '\x2', 
		'T', 'U', '\a', 'U', '\x2', '\x2', 'U', 'V', '\a', 'k', '\x2', '\x2', 
		'V', '\f', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 'U', '\x2', '\x2', 
		'X', 'Y', '\a', 'k', '\x2', '\x2', 'Y', 'Z', '\a', 'p', '\x2', '\x2', 
		'Z', '[', '\a', 'q', '\x2', '\x2', '[', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\\', ']', '\a', '-', '\x2', '\x2', ']', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '^', '_', '\a', '/', '\x2', '\x2', '_', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\a', ',', '\x2', '\x2', '\x61', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x63', '\a', '\x31', '\x2', '\x2', '\x63', '\x16', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '\'', '\x2', '\x2', 
		'\x65', '\x18', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', '(', '\x2', 
		'\x2', 'g', 'h', '\a', '(', '\x2', '\x2', 'h', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', '~', '\x2', '\x2', 'j', 'k', '\a', '~', '\x2', 
		'\x2', 'k', '\x1C', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '#', '\x2', 
		'\x2', 'm', '\x1E', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', '@', '\x2', 
		'\x2', 'o', ' ', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '>', '\x2', 
		'\x2', 'q', '\"', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '@', '\x2', 
		'\x2', 's', 't', '\a', '?', '\x2', '\x2', 't', '$', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '>', '\x2', '\x2', 'v', 'w', '\a', '?', '\x2', 
		'\x2', 'w', '&', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', '?', '\x2', 
		'\x2', 'y', 'z', '\a', '?', '\x2', '\x2', 'z', '(', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '#', '\x2', '\x2', '|', '}', '\a', '?', '\x2', 
		'\x2', '}', '*', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', '?', '\x2', 
		'\x2', '\x7F', ',', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', 
		'}', '\x2', '\x2', '\x81', '.', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', 
		'\a', '\x7F', '\x2', '\x2', '\x83', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x84', '\x85', '\a', '*', '\x2', '\x2', '\x85', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x86', '\x87', '\a', '+', '\x2', '\x2', '\x87', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '=', '\x2', '\x2', '\x89', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', 'v', '\x2', 
		'\x2', '\x8B', '\x8C', '\a', 't', '\x2', '\x2', '\x8C', '\x8D', '\a', 
		'w', '\x2', '\x2', '\x8D', '\x94', '\a', 'g', '\x2', '\x2', '\x8E', '\x8F', 
		'\a', 'h', '\x2', '\x2', '\x8F', '\x90', '\a', '\x63', '\x2', '\x2', '\x90', 
		'\x91', '\a', 'n', '\x2', '\x2', '\x91', '\x92', '\a', 'u', '\x2', '\x2', 
		'\x92', '\x94', '\a', 'g', '\x2', '\x2', '\x93', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x94', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\x95', '\x99', '\t', '\x2', '\x2', '\x2', 
		'\x96', '\x98', '\t', '\x3', '\x2', '\x2', '\x97', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\x3', '\x2', '\x2', '\x2', 
		'\x9A', ':', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x9E', '\t', '\x4', '\x2', '\x2', '\x9D', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', 
		'\x2', '\x2', '\xA0', '<', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA3', 
		'\t', '\x5', '\x2', '\x2', '\xA2', '\xA1', '\x3', '\x2', '\x2', '\x2', 
		'\xA3', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\b', '\x1F', '\x2', '\x2', 
		'\xA7', '>', '\x3', '\x2', '\x2', '\x2', '\a', '\x2', '\x93', '\x99', 
		'\x9F', '\xA4', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ParserJava
