//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/marco/Desktop/Interpretador MACOY/MACOY/MACOY\MACOY.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ParserJava {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MACOYParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IMACOYVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] MACOYParser.ProgramaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencia([NotNull] MACOYParser.SentenciaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.declaraciondevariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaraciondevariable([NotNull] MACOYParser.DeclaraciondevariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.asignaciondevariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignaciondevariable([NotNull] MACOYParser.AsignaciondevariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.imprimir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImprimir([NotNull] MACOYParser.ImprimirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.condicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondicional([NotNull] MACOYParser.CondicionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresion([NotNull] MACOYParser.ExpresionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparacion([NotNull] MACOYParser.ComparacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.logicas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicas([NotNull] MACOYParser.LogicasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.operacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperacion([NotNull] MACOYParser.OperacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.operacionBinaria"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperacionBinaria([NotNull] MACOYParser.OperacionBinariaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MACOYParser.operacionComparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperacionComparacion([NotNull] MACOYParser.OperacionComparacionContext context);
}
} // namespace ParserJava
