//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/marco/Desktop/Interpretador MACOY/MACOY/MACOY\MACOY.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMACOYListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class MACOYBaseListener : IMACOYListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrograma([NotNull] MACOYParser.ProgramaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.programa"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrograma([NotNull] MACOYParser.ProgramaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentencia([NotNull] MACOYParser.SentenciaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentencia([NotNull] MACOYParser.SentenciaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.declaraciondevariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaraciondevariable([NotNull] MACOYParser.DeclaraciondevariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.declaraciondevariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaraciondevariable([NotNull] MACOYParser.DeclaraciondevariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.asignaciondevariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsignaciondevariable([NotNull] MACOYParser.AsignaciondevariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.asignaciondevariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsignaciondevariable([NotNull] MACOYParser.AsignaciondevariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.imprimir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImprimir([NotNull] MACOYParser.ImprimirContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.imprimir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImprimir([NotNull] MACOYParser.ImprimirContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.condicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicional([NotNull] MACOYParser.CondicionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.condicional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicional([NotNull] MACOYParser.CondicionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpresion([NotNull] MACOYParser.ExpresionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.expresion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpresion([NotNull] MACOYParser.ExpresionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.comparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparacion([NotNull] MACOYParser.ComparacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.comparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparacion([NotNull] MACOYParser.ComparacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.logicas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicas([NotNull] MACOYParser.LogicasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.logicas"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicas([NotNull] MACOYParser.LogicasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.operacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperacion([NotNull] MACOYParser.OperacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.operacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperacion([NotNull] MACOYParser.OperacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.operacionBinaria"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperacionBinaria([NotNull] MACOYParser.OperacionBinariaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.operacionBinaria"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperacionBinaria([NotNull] MACOYParser.OperacionBinariaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.operacionComparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperacionComparacion([NotNull] MACOYParser.OperacionComparacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.operacionComparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperacionComparacion([NotNull] MACOYParser.OperacionComparacionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
