//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/marco/Desktop/Interpretador MACOY/MACOY/MACOY\MACOY.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MACOYParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IMACOYListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] MACOYParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] MACOYParser.ProgramaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSentencia([NotNull] MACOYParser.SentenciaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSentencia([NotNull] MACOYParser.SentenciaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.declaraciondevariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaraciondevariable([NotNull] MACOYParser.DeclaraciondevariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.declaraciondevariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaraciondevariable([NotNull] MACOYParser.DeclaraciondevariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.asignaciondevariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsignaciondevariable([NotNull] MACOYParser.AsignaciondevariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.asignaciondevariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsignaciondevariable([NotNull] MACOYParser.AsignaciondevariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.imprimir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImprimir([NotNull] MACOYParser.ImprimirContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.imprimir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImprimir([NotNull] MACOYParser.ImprimirContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.condicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondicional([NotNull] MACOYParser.CondicionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.condicional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondicional([NotNull] MACOYParser.CondicionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresion([NotNull] MACOYParser.ExpresionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresion([NotNull] MACOYParser.ExpresionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparacion([NotNull] MACOYParser.ComparacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparacion([NotNull] MACOYParser.ComparacionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.logicas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicas([NotNull] MACOYParser.LogicasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.logicas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicas([NotNull] MACOYParser.LogicasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.operacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperacion([NotNull] MACOYParser.OperacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.operacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperacion([NotNull] MACOYParser.OperacionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.operacionBinaria"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperacionBinaria([NotNull] MACOYParser.OperacionBinariaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.operacionBinaria"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperacionBinaria([NotNull] MACOYParser.OperacionBinariaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MACOYParser.operacionComparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperacionComparacion([NotNull] MACOYParser.OperacionComparacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MACOYParser.operacionComparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperacionComparacion([NotNull] MACOYParser.OperacionComparacionContext context);
}
